# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoLinha', models.CharField(max_length=10)),
                ('Origem', models.CharField(max_length=200)),
                ('Retorno', models.CharField(max_length=200)),
                ('Zona', models.CharField(max_length=200)),
                ('Denomicao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LinhaOnibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=30)),
                ('Denomicao', models.CharField(max_length=200)),
                ('Zona', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoParada', models.CharField(max_length=15)),
                ('Denomicao', models.CharField(max_length=250)),
                ('Endereco', models.CharField(max_length=250, null=True)),
                ('Lat', models.CharField(max_length=30, null=True)),
                ('Long', models.CharField(max_length=30, null=True)),
                ('LinhaOnibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Linha', to='bus.LinhaOnibus')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('img', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoVeiculo', models.CharField(max_length=10)),
                ('Lat', models.CharField(max_length=30)),
                ('Long', models.CharField(max_length=30)),
                ('Hora', models.CharField(max_length=30)),
                ('Cadeirante', models.BooleanField(default=False)),
                ('Linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Veiculos', to='bus.Linha')),
            ],
        ),
    ]
