# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradas',
            name='LinhaOnibus',
        ),
        migrations.AddField(
            model_name='linhaonibus',
            name='Parada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Paradas', to='bus.Paradas'),
        ),
    ]
