# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20170315_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnibusInfoArAdpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.CharField(max_length=20)),
                ('adptado', models.BooleanField(default=False)),
                ('ar', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='linhaonibus',
            name='Parada',
        ),
    ]
